<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kayt Ol</name>
   <tag></tag>
   <elementGuidId>7a534e1b-aa6b-4b97-92f2-738f1f881d4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='kayitol-tab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kayitol-tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f0aeabd6-678c-465b-a6ac-899c8d737ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link active</value>
      <webElementGuid>d127e3d1-07d5-4a88-a3f0-d58193a84b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kayitol-tab</value>
      <webElementGuid>841f070f-3db8-4db3-bd1a-2234ba466453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>7698efd2-1077-4974-9b50-b301783ec989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#kayitol</value>
      <webElementGuid>0501d8ea-a152-4daf-8273-b454f835e391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>85e33a09-5607-4d7d-8e3a-89600d418452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>6cc3e6ca-74be-4eae-8039-3b6e40503e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>kayitol</value>
      <webElementGuid>fa81dd9f-5df0-40f3-9358-0f5645c28629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d5b93c45-4683-4316-9961-6e2f8f0801d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kayıt Ol</value>
      <webElementGuid>1b2ff44a-6d6f-4e89-8721-658e69317edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form-area&quot;)/div[@class=&quot;container&quot;]/ul[@id=&quot;myTab&quot;]/li[@class=&quot;nav-item&quot;]/button[@id=&quot;kayitol-tab&quot;]</value>
      <webElementGuid>afdcf337-cd33-4b08-bd70-4f97539b0e79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='kayitol-tab']</value>
      <webElementGuid>10eaad49-4b45-4e86-8d49-6c7b0b7b24bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='myTab']/li[2]/button</value>
      <webElementGuid>a4177d66-6d24-4526-8f71-4d1387138516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Üye Girişi'])[1]/following::button[1]</value>
      <webElementGuid>b3ea5dd2-5c8b-4895-add3-646e5557db8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giriş'])[1]/following::button[2]</value>
      <webElementGuid>296d52db-ffd4-4156-9f0f-c1690c290b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ÜYE GİRİŞİ'])[1]/preceding::button[1]</value>
      <webElementGuid>b87767c6-0303-43ab-a704-8b5d7692b2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-Mail:'])[1]/preceding::button[1]</value>
      <webElementGuid>353c03ee-4686-42e2-a86e-c9b66e9f7701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kayıt Ol']/parent::*</value>
      <webElementGuid>473dceb9-8ed2-4253-b867-8972459b42a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button</value>
      <webElementGuid>aaf79f38-36bc-4a46-b10a-bb111556407e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'kayitol-tab' and @type = 'button' and (text() = 'Kayıt Ol' or . = 'Kayıt Ol')]</value>
      <webElementGuid>3e64f524-5ac1-464b-8d3e-d5ddc3673b79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
