<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_accept-privacy-policy</name>
   <tag></tag>
   <elementGuidId>eb27d887-3b93-4de8-b625-fe33803af913</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accept-privacy-policy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accept-privacy-policy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b1e9b46-b59a-4231-9142-7d23c07c95f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-check__input</value>
      <webElementGuid>f5110f6a-1cdb-4b96-85d2-1c9ff085d013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accept-privacy-policy</value>
      <webElementGuid>6d01eb97-4a5b-4896-9392-dad5d733fde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accept-privacy-policy</value>
      <webElementGuid>87f4da2d-2ee5-4a89-8422-d57d67899563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e4893d74-accd-4c61-b374-2108c2f99072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept-privacy-policy&quot;)</value>
      <webElementGuid>f567e27a-5585-4223-bfba-76b3ebea103a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accept-privacy-policy']</value>
      <webElementGuid>d4077210-cf80-438b-8f8b-2736ba1fce47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='RegisterForm']/div/div/div[2]/div[8]/div/span/span/input</value>
      <webElementGuid>7351e503-176c-4191-8883-b4c4a0a3d2e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/span/span/input</value>
      <webElementGuid>0805aeac-ef5a-4d37-a205-d7f833808fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accept-privacy-policy' and @name = 'accept-privacy-policy' and @type = 'checkbox']</value>
      <webElementGuid>62c8cd10-9038-4f27-bace-89b48f8cbf43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
