<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ifre_Password</name>
   <tag></tag>
   <elementGuidId>bbacfe32-2186-4e16-aa3f-d026b6afe8ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Password'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-6.mb-4 > #Password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>428006ea-eb2e-4a8b-a5b0-632927d3fb3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control password</value>
      <webElementGuid>bf203d47-bac2-464d-b254-d2e0f5bd9351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>72a0cd23-52ef-40fa-9a7c-a1affbcab932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>67897834-59b9-46d5-b684-1fcb88a0a8ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>Şifre en az 6 karakter içermelidir.</value>
      <webElementGuid>0fff167e-a9e1-4ff9-a6ad-478b3a1f8fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>999</value>
      <webElementGuid>e114f342-4e79-4a8b-9f75-67ce6bb97388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-min</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>a72f97a9-2605-4994-8fe0-6765cba9c0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Şifre gereklidir.</value>
      <webElementGuid>9a5b94da-6076-481d-9987-535616260646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>c19cce54-db16-4cf3-812a-28db9d593c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>b0b2ab95-5bde-40d3-a29d-33f79786260b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RegisterForm&quot;)/div[@class=&quot;card-body&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 mb-4&quot;]/input[@id=&quot;Password&quot;]</value>
      <webElementGuid>b36e2f21-4c0e-4454-9a88-c1a26f447662</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Password'])[2]</value>
      <webElementGuid>a9a2ede5-a4a8-444c-b803-c8e0dc8b6af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='RegisterForm']/div/div/div[2]/div[4]/input</value>
      <webElementGuid>7594f104-94a4-433d-bac1-b3899705b61d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/input</value>
      <webElementGuid>b23979ac-060d-47df-bd10-b26ec17eb09f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'Password' and @name = 'Password']</value>
      <webElementGuid>455d076e-62ad-4e4c-9cd3-133762e2638f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
