<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Logo_q</name>
   <tag></tag>
   <elementGuidId>de5f8751-c639-4063-8c97-16232cb876d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search--input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search--input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9b6f177-69a4-403c-b1bb-9bf325d53caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search__input</value>
      <webElementGuid>f8a4fc03-9841-4cd8-9f33-f11ea88346db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search--input</value>
      <webElementGuid>bb1e1e5b-14b9-4cc9-85b7-2286f110bc65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a881fc65-7190-4c49-801e-9303e4eeccc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>142c8264-e79b-4879-95b3-47708404468c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>76669610-9b9e-48e4-b4d1-2f3304681fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ara...</value>
      <webElementGuid>f37a0841-7a6c-4e1f-875f-1d90395c637a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search--input&quot;)</value>
      <webElementGuid>07fc16ea-f177-4250-9bf3-4734f88f50a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search--input']</value>
      <webElementGuid>b1f9406a-6aa2-41e1-9247-6f52341ef377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='small-search-box-form']/input[2]</value>
      <webElementGuid>fc088ffa-df9d-47f5-afda-0634bebc00d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>70716247-7508-488c-b6c7-661e0ad5c13f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search--input' and @type = 'text' and @name = 'q' and @placeholder = 'Ara...']</value>
      <webElementGuid>0de82444-9b9a-4163-9c8c-1ce79c4427cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
