<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Erkek</name>
   <tag></tag>
   <elementGuidId>2d0f2ebc-d1ed-48ad-864b-27271cdfca46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar-inner']/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>21b2caca-5112-49e2-8443-065df2ede218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>4e2e7aca-3913-4117-bb61-ca2408a1c42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Erkek</value>
      <webElementGuid>75dcffed-5d65-4ddc-b931-ea7f263cf828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-inner&quot;)/div[@class=&quot;sidebar-inner__top&quot;]/div[@class=&quot;sidebar-inner__top--item&quot;]/a[1]</value>
      <webElementGuid>46dfde5d-6063-448b-924e-435ee38c2cbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-inner']/div/div[2]/a</value>
      <webElementGuid>71685107-ec4f-4aa0-a663-3c086ad24266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Erkek')]</value>
      <webElementGuid>dfdcef97-5acf-4a60-90ad-8f6c9c75684e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Defyallday'])[1]/following::a[1]</value>
      <webElementGuid>38a6d0bc-5c08-42b6-9017-8c8722f7810b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phantom'])[1]/following::a[2]</value>
      <webElementGuid>9b3b8ef0-72fa-4593-b3aa-465dc32178b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ayakkabı'])[2]/preceding::a[1]</value>
      <webElementGuid>a31c734b-97ad-48f2-891f-f617d8011760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sneaker'])[2]/preceding::a[2]</value>
      <webElementGuid>7a4b767a-16e2-4811-b176-14d6462d2db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Erkek']/parent::*</value>
      <webElementGuid>71e72824-9294-4911-a0e7-75edd73403e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[4]</value>
      <webElementGuid>491b54a1-2234-4ffc-811a-351ca3c7f4d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/a</value>
      <webElementGuid>0f303a9e-cbff-4ef8-85e5-78176fd5cc5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Erkek' or . = 'Erkek')]</value>
      <webElementGuid>ecbfa25a-c37b-4547-a77a-0e46549c438a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
