<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sepete Ekle (1)</name>
   <tag></tag>
   <elementGuidId>8c79c5cf-f72a-4000-a009-a6ff528cf77a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-to-cart-button-03fc7478-e0d8-46f1-aa7f-fe9122f3d53a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='add-to-cart-button-03fc7478-e0d8-46f1-aa7f-fe9122f3d53a']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>466daf3a-19d2-4717-ac68-31bfad8bf786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1042fc4f-cc09-4c8d-8486-85be396de45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-to-cart-button-03fc7478-e0d8-46f1-aa7f-fe9122f3d53a</value>
      <webElementGuid>bafac92e-ff03-44da-bae2-8c4492eeaa92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-lg add-to-cart-button</value>
      <webElementGuid>10042f5d-075f-4ee0-a86d-9cbc88ad7447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productid</name>
      <type>Main</type>
      <value>03fc7478-e0d8-46f1-aa7f-fe9122f3d53a</value>
      <webElementGuid>b1299ed2-687b-4619-b3a1-32ce6e974174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AjaxCart.addproducttocart_details('/addproducttocart/details/03fc7478-e0d8-46f1-aa7f-fe9122f3d53a/1', '#product-details-form');return false;</value>
      <webElementGuid>8b52d195-adee-41ab-86e5-41a1a684dca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Sepete Ekle
                </value>
      <webElementGuid>e9924891-aa95-41ae-8921-f9e7fd19161f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-to-cart-button-03fc7478-e0d8-46f1-aa7f-fe9122f3d53a&quot;)</value>
      <webElementGuid>02c303b9-aa0e-4efc-9d20-7a874ad27cc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='add-to-cart-button-03fc7478-e0d8-46f1-aa7f-fe9122f3d53a']</value>
      <webElementGuid>b0515305-1535-437f-9f3a-378a05707942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div[2]/div[4]/div/div/button</value>
      <webElementGuid>346af819-6974-4195-8a80-f60621a1bf86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beden Tablosu'])[1]/following::button[1]</value>
      <webElementGuid>f1ea823d-c9ed-41ff-aa48-6e2c79026039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='H04251-W-001'])[1]/following::button[1]</value>
      <webElementGuid>f3e3780e-15a4-4d37-9585-72c270ae0254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stoka Gelince Haber Ver'])[1]/preceding::button[1]</value>
      <webElementGuid>09a5694e-d56c-4b21-bde2-fd7ce7ce67d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/button</value>
      <webElementGuid>8b7ad354-a9d5-4152-b36c-bd3f10195b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'add-to-cart-button-03fc7478-e0d8-46f1-aa7f-fe9122f3d53a' and (text() = '
                    Sepete Ekle
                ' or . = '
                    Sepete Ekle
                ')]</value>
      <webElementGuid>d8346d18-a058-4d10-ad41-d55e19e31cae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
