<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kaydet</name>
   <tag></tag>
   <elementGuidId>3a615c5d-07c2-44e3-aca8-3406a09624bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnShippingSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnShippingSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>409e3ecc-4799-49b8-9238-fed1ac90abe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary reset</value>
      <webElementGuid>e2cd7604-30c1-468c-816d-252cf8337669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnShippingSubmit</value>
      <webElementGuid>1956734b-78c5-4d39-b3a9-37af4394309d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Shipping.submit()</value>
      <webElementGuid>04fe0027-3471-439e-94eb-5d251a2df066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>561df07d-8c44-427c-bbe8-81cb6eeb4f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kaydet</value>
      <webElementGuid>53c3f1a0-0b90-4241-aacc-39e8c483e051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnShippingSubmit&quot;)</value>
      <webElementGuid>bb526b75-1bdf-4473-9509-bc9513a6a47e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnShippingSubmit']</value>
      <webElementGuid>1cb28157-a718-480c-b259-e64b0b200148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shipAddress']/button</value>
      <webElementGuid>e645f31e-a88e-4fa9-8181-e9e0a4107a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T.C. Kimlik No'])[1]/following::button[1]</value>
      <webElementGuid>400d58c0-4558-4a07-a397-fbb717a5da8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vergi Dairesi:'])[1]/following::button[1]</value>
      <webElementGuid>7a9edec4-6416-45d3-b3a0-852c89225585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kredi Kartı'])[1]/preceding::button[1]</value>
      <webElementGuid>ce88e80b-9fcf-4da0-8341-d945d22ac944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iyzico ile öde'])[1]/preceding::button[1]</value>
      <webElementGuid>1807ef06-2e6a-4056-b70b-0ba2363284d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kaydet']/parent::*</value>
      <webElementGuid>47612292-5aca-47f4-bfbe-8def458161f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/form/button</value>
      <webElementGuid>45f01127-29cc-4f51-b5a0-f810417b420f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnShippingSubmit' and @type = 'button' and (text() = 'Kaydet' or . = 'Kaydet')]</value>
      <webElementGuid>ce38e28a-25de-412b-8656-ccb4c19a7f6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
