<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ayakkab</name>
   <tag></tag>
   <elementGuidId>0c4938f0-fca8-4f94-bc8b-95eb0490b287</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-body']/div/div/div/div/nav/ol/li[3]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a1ebedc5-bddc-4b62-b9ed-73fc290a94a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>90b7a4c4-2c70-4112-b49f-e47a1c0c13f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ayakkabı</value>
      <webElementGuid>7d6ab13e-57f0-4079-9ade-cddb959fb480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-body&quot;)/div[@class=&quot;category-banner&quot;]/div[@class=&quot;page-header&quot;]/div[@class=&quot;page-header__container container&quot;]/div[@class=&quot;page-header__breadcrumb&quot;]/nav[1]/ol[@class=&quot;breadcrumb&quot;]/li[@class=&quot;breadcrumb-item&quot;]/a[1]/span[1]</value>
      <webElementGuid>290f3ca8-5fc4-4752-8fc8-1c4885636e24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-body']/div/div/div/div/nav/ol/li[3]/a/span</value>
      <webElementGuid>9c33eb00-47e0-4bf1-897f-b6568bb9fa76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Erkek'])[2]/following::span[1]</value>
      <webElementGuid>f99214f1-733e-4bae-90a5-aee042d99c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sneaker'])[4]/preceding::span[1]</value>
      <webElementGuid>4121e835-edaa-470f-a3f4-0b327052fcd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li[3]/a/span</value>
      <webElementGuid>1a8397f1-d00c-40b8-98e1-392afb1d55c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ayakkabı' or . = 'Ayakkabı')]</value>
      <webElementGuid>6264fe1d-a710-447f-8af0-00b75b128320</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
