<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sepete Ekle (1)</name>
   <tag></tag>
   <elementGuidId>e76447e9-4f6a-4bee-b411-5c8a2f413083</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-to-cart-button-03fc7478-e0d8-46f1-aa7f-fe9122f3d53a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9eb59ec8-3e4e-4206-b2d2-92c419b880b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sepete Ekle</value>
      <webElementGuid>819dc070-817c-4b7f-a1ab-868b3c6948f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-to-cart-button-03fc7478-e0d8-46f1-aa7f-fe9122f3d53a&quot;)/span[1]</value>
      <webElementGuid>f3825a2c-922e-4e52-a55d-7969a7ec07b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='add-to-cart-button-03fc7478-e0d8-46f1-aa7f-fe9122f3d53a']/span</value>
      <webElementGuid>7e4e6ea8-d174-4c7e-8ef3-6c2bc56bf019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beden Tablosu'])[1]/following::span[8]</value>
      <webElementGuid>0fd89d78-f20e-47ae-ba74-cb27e7d80bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='H04251-W-001'])[1]/following::span[8]</value>
      <webElementGuid>a68c425d-cac7-4682-9192-f0f379f335e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stoka Gelince Haber Ver'])[1]/preceding::span[1]</value>
      <webElementGuid>06cad924-b93a-4f54-bb39-93d94c60b605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sepete Ekle']/parent::*</value>
      <webElementGuid>d215c478-2984-4b24-843e-376da3425aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/button/span</value>
      <webElementGuid>8da2d196-e8db-4819-b56e-f7b5047012a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Sepete Ekle' or . = 'Sepete Ekle')]</value>
      <webElementGuid>ec6a2e54-d0ae-48eb-85f3-abdba8e51bba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
