<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>use</name>
   <tag></tag>
   <elementGuidId>4d07d968-7ed3-43f3-a339-7b23ec472e1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>use</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[@class=&quot;is-ready&quot;]/div[@class=&quot;site&quot;]/header[@class=&quot;site__header&quot;]/div[@class=&quot;site-header&quot;]/div[@class=&quot;site-header__nav-panel&quot;]/div[@class=&quot;nav-panel&quot;]/div[@class=&quot;nav-panel__container container&quot;]/div[@class=&quot;nav-panel__row&quot;]/div[@class=&quot;nav-panel__menu_opener&quot;]/button[@class=&quot;mobile-header__menu-button&quot;]/svg[@class=&quot;d-none d-sm-block&quot;]/use[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>use</value>
      <webElementGuid>795c1159-7931-4186-86af-717505c93ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>30px</value>
      <webElementGuid>27ab7247-4c7c-435d-8ab2-74ad523e1494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>17px</value>
      <webElementGuid>4f00a686-3597-4147-8594-4f3e8966cf50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xlink:href</name>
      <type>Main</type>
      <value>/Themes/Sportime/Content/images/sportime/icons/bars.svg#bars</value>
      <webElementGuid>76783a27-aeb6-48e1-a51e-2f380a46bd4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;is-ready&quot;]/div[@class=&quot;site&quot;]/header[@class=&quot;site__header&quot;]/div[@class=&quot;site-header&quot;]/div[@class=&quot;site-header__nav-panel&quot;]/div[@class=&quot;nav-panel&quot;]/div[@class=&quot;nav-panel__container container&quot;]/div[@class=&quot;nav-panel__row&quot;]/div[@class=&quot;nav-panel__menu_opener&quot;]/button[@class=&quot;mobile-header__menu-button&quot;]/svg[@class=&quot;d-none d-sm-block&quot;]/use[1]</value>
      <webElementGuid>6e7f320e-f645-4cd4-a8b3-fae329c06db0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
