<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_selected_second_product</name>
   <tag></tag>
   <elementGuidId>a1371b4b-14be-428c-b528-a76c1fa6255f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@class='product-info-detail'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.product-info-detail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>18235b11-5e04-412f-8816-416f2b1f372b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-info-detail</value>
      <webElementGuid>a61de2cd-0485-4a4b-9b13-c9f11b80147c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/nike-w-blazer-low-platform-dj0292-101-kadin-sneaker</value>
      <webElementGuid>baf32ef3-690f-4129-a042-18e62c1af4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nike W Blazer Low Platform</value>
      <webElementGuid>973767d1-fe8a-49d5-899d-5ff393675a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-body&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;shop-layout shop-layout--sidebar--start&quot;]/div[@class=&quot;shop-layout__content&quot;]/div[@class=&quot;block&quot;]/div[@class=&quot;category-page&quot;]/div[@class=&quot;products-view&quot;]/div[@class=&quot;products-view__list products-list&quot;]/div[@class=&quot;products-list__body&quot;]/div[@class=&quot;products-list__item&quot;]/div[@class=&quot;product-card product-card--hidden-actions&quot;]/div[@class=&quot;product-card__info&quot;]/div[@class=&quot;product-card__name&quot;]/a[@class=&quot;product-info-detail&quot;]</value>
      <webElementGuid>57baab6b-e197-4b5c-b754-7ab2c86a643f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-body']/div[2]/div/div[2]/div/div/div/div[2]/div[2]/div/div/div[3]/div/a</value>
      <webElementGuid>a7cf68fd-8a9a-4c40-8bfc-901c1e44c0ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Nike W Blazer Low Platform')]</value>
      <webElementGuid>04116bca-d401-48f1-8492-70b6efbce974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtreleri Göster'])[1]/following::a[2]</value>
      <webElementGuid>dc074f79-1f3d-48c2-8959-6bfe6287888c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ürün Sıralaması'])[2]/following::a[2]</value>
      <webElementGuid>904d5844-c677-4321-89ae-83d475a02545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Renk:'])[1]/preceding::a[1]</value>
      <webElementGuid>0abd1da0-c41d-429d-b8a6-7874079ab8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nike W Blazer Low Platform']/parent::*</value>
      <webElementGuid>c74dabce-fd93-404b-a306-8d9977288723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/nike-w-blazer-low-platform-dj0292-101-kadin-sneaker')])[2]</value>
      <webElementGuid>0f4ca95d-5455-45bb-a7eb-698b2e444329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>a8e8b6e7-ed4a-4af7-9a60-d7bcf9616130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/nike-w-blazer-low-platform-dj0292-101-kadin-sneaker' and (text() = 'Nike W Blazer Low Platform' or . = 'Nike W Blazer Low Platform')]</value>
      <webElementGuid>2ee898dd-7901-40c3-a103-dbf18ad3ec9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
