<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sepete Ekle</name>
   <tag></tag>
   <elementGuidId>257efd53-3c1b-4dfc-bca6-b892764d25ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='add-to-cart-button-81c8f559-f8b4-4431-a651-52b0109bad2e']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add-to-cart-button-81c8f559-f8b4-4431-a651-52b0109bad2e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>600acf50-ac92-4a2d-b19b-51ffcb5ecb40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>419f0feb-8c03-48da-98ed-5cbdf850d499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-to-cart-button-81c8f559-f8b4-4431-a651-52b0109bad2e</value>
      <webElementGuid>1e0ae752-c574-4717-b0b9-67d8a6bc67c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-lg add-to-cart-button</value>
      <webElementGuid>8a53c8e0-851e-47b7-8ef0-69fa6c99b476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productid</name>
      <type>Main</type>
      <value>81c8f559-f8b4-4431-a651-52b0109bad2e</value>
      <webElementGuid>3a014a28-3b70-465d-9285-55ba1e01038e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AjaxCart.addproducttocart_details('/addproducttocart/details/81c8f559-f8b4-4431-a651-52b0109bad2e/1', '#product-details-form');return false;</value>
      <webElementGuid>efd91fe8-5ce7-4cff-8e12-d4729c3be30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Sepete Ekle
                </value>
      <webElementGuid>16743403-542e-4aca-a95c-4eece4ae9949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-to-cart-button-81c8f559-f8b4-4431-a651-52b0109bad2e&quot;)</value>
      <webElementGuid>cd237e7c-fb0d-4d3f-90db-89f368552935</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='add-to-cart-button-81c8f559-f8b4-4431-a651-52b0109bad2e']</value>
      <webElementGuid>105b81f2-c6ea-4c4c-83aa-e15acae38529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div[2]/div[4]/div/div/button</value>
      <webElementGuid>9928500a-8d4f-43ec-b447-c9b86dc5b1eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beden Tablosu'])[1]/following::button[1]</value>
      <webElementGuid>79cf067c-c98f-4ade-8643-0a593f05012e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DJ0292-100'])[1]/following::button[1]</value>
      <webElementGuid>2815b423-368c-44a5-b3df-f5c1aaad9323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stoka Gelince Haber Ver'])[1]/preceding::button[1]</value>
      <webElementGuid>02cdeaf7-00c1-4daf-bf30-080b1585c636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/button</value>
      <webElementGuid>980b4e18-68e3-479a-b920-d1b27d95955f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'add-to-cart-button-81c8f559-f8b4-4431-a651-52b0109bad2e' and (text() = '
                    Sepete Ekle
                ' or . = '
                    Sepete Ekle
                ')]</value>
      <webElementGuid>ad96e7c8-9e15-43f7-9fdf-b437a449343b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
