<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sepete Git</name>
   <tag></tag>
   <elementGuidId>9e9c09c5-7d8d-4735-849c-836c153c99ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-dark.w-100.d-flex.justify-content-center.mx-3.border-left-0.rounded-3.btn-lg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[32]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0a921a62-8c0f-4ba8-9a3d-c6a3abb0e8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9aaa69e3-ccf5-4c36-b19f-03b51318605d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-dark w-100 d-flex justify-content-center mx-3 border-left-0 rounded-3 btn-lg</value>
      <webElementGuid>b59bcd75-b5cd-4f7d-8421-59d9e4f81a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setLocation('/cart')</value>
      <webElementGuid>3dd22446-135d-4467-9ab8-c065cf1bb880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sepete Git</value>
      <webElementGuid>dcf600a6-2b53-4af1-9295-66d74f74f882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ModalAddToCart&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;modal-footer px-0 pb-0 mt-0&quot;]/div[@class=&quot;btn-group col-8 px-0 mx-auto my-0&quot;]/button[@class=&quot;btn btn-dark w-100 d-flex justify-content-center mx-3 border-left-0 rounded-3 btn-lg&quot;]</value>
      <webElementGuid>848c8156-d957-4070-8d06-7715a93e3a80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[32]</value>
      <webElementGuid>58958e24-3066-465b-b202-6911dd5effb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalAddToCart']/div/div/div[2]/div[4]/div/button[2]</value>
      <webElementGuid>5523257b-3572-4d05-8675-b486bf29ede0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alışverişe Devam et'])[1]/following::button[1]</value>
      <webElementGuid>c8dd71a5-8406-4ae5-b6e3-9a3b2a488282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='›'])[5]/following::button[7]</value>
      <webElementGuid>42362347-c9e4-4116-84b9-76cd7b9ece02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sepete Git']/parent::*</value>
      <webElementGuid>bb671069-499a-4a7d-a6a0-a94d0d0c2a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button[2]</value>
      <webElementGuid>5cf1b23f-13d4-4909-ae1d-e36689193ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Sepete Git' or . = 'Sepete Git')]</value>
      <webElementGuid>97d67d1b-af09-4aa9-a61d-03089f513c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[17]</value>
      <webElementGuid>a8d6544f-770c-4281-9582-217807e0cf08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalAddToCart']/div/div/div[2]/div[3]/div/button[2]</value>
      <webElementGuid>8a5f864e-83ab-458b-ab5c-09441698c211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beyaz'])[4]/following::button[2]</value>
      <webElementGuid>1fb44c71-2660-4a25-8bf0-874b4e3bc0ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button[2]</value>
      <webElementGuid>44de672c-20fb-45e4-9238-5653755372ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
