<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cart_quantity_control</name>
   <tag></tag>
   <elementGuidId>23121074-0a4e-499c-81b0-f2b1a4886c47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='shopping-cart-form']/div/div/div/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>c6a4d78f-5368-40ca-b1a9-0cfacdea06c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 1 Adet</value>
      <webElementGuid>606257de-678f-4d18-8993-01ce2e9cc940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart-form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shopping-cart-container&quot;]/div[@class=&quot;shopping-cart-container-totalitems&quot;]/strong[1]</value>
      <webElementGuid>d72ab015-a867-4b30-845f-907b57704a7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shopping-cart-form']/div/div/div/strong</value>
      <webElementGuid>d1056804-0136-43a5-b726-fd699654984d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nike W Blazer Low Platform'])[1]/preceding::strong[1]</value>
      <webElementGuid>362598d0-4016-4180-a20a-2be186bca04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DJ029210038'])[1]/preceding::strong[1]</value>
      <webElementGuid>a67d064c-4a5e-4342-b2f0-2ef56c34c5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1 Adet']/parent::*</value>
      <webElementGuid>5eefa1c1-af71-48ae-84cf-b89308f11f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>350b0274-1d14-4f50-ba9a-6113d3d4ed99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = ' 1 Adet' or . = ' 1 Adet')]</value>
      <webElementGuid>cddc36c1-c748-438e-a05d-8972ea639b24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
