<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sepetinde  1 Adet rn bulunuyor</name>
   <tag></tag>
   <elementGuidId>9a60ef8f-76cf-405c-bcf5-517a34a56246</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='shopping-cart-form']/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.shopping-cart-container-totalitems</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1a4f0d1d-c290-4779-9c54-c75343a67c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shopping-cart-container-totalitems</value>
      <webElementGuid>15f25af5-c92d-429b-b16a-3cd370943fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sepetinde  1 Adet ürün bulunuyor</value>
      <webElementGuid>575c79e3-855b-4356-bbf2-53094c31e8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart-form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;shopping-cart-container&quot;]/div[@class=&quot;shopping-cart-container-totalitems&quot;]</value>
      <webElementGuid>98c5469e-f99e-4007-a04b-f6620bf1d349</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shopping-cart-form']/div/div/div</value>
      <webElementGuid>08b11c37-8e86-4e32-8868-9db353a5e4ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nike W Blazer Low Platform'])[1]/preceding::div[1]</value>
      <webElementGuid>9bc4c2c7-86df-4cbc-830f-f5e1559c91fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DJ029210038'])[1]/preceding::div[1]</value>
      <webElementGuid>51cb6015-677d-4ac0-a2f2-0965fbb81906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sepetinde']/parent::*</value>
      <webElementGuid>a9d23e01-958e-4b4a-b10d-ad28e425257f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div</value>
      <webElementGuid>a2201a7e-9112-41d3-992d-d48cc772698e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sepetinde  1 Adet ürün bulunuyor' or . = 'Sepetinde  1 Adet ürün bulunuyor')]</value>
      <webElementGuid>2e509917-24c0-4998-aefd-89dbe09c58da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
