<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kaydet</name>
   <tag></tag>
   <elementGuidId>3e1990e5-c78b-41f5-b76a-63a2cb92d189</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ShippingSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ShippingSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a4247582-8b79-44af-8326-3d09f024b3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary reset</value>
      <webElementGuid>45a4b092-aee5-4603-813b-4cb0545e0b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ShippingSubmit</value>
      <webElementGuid>f84212bd-b364-46ce-9d45-5f3f69faf877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Shipping.submit()</value>
      <webElementGuid>9312c98a-1c5d-4c0c-a041-e9af28384c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>84470ed3-7d91-4816-8893-a70d8d1c7973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kaydet</value>
      <webElementGuid>32b7cbe7-1733-4c31-91fe-9d73bdaa80e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ShippingSubmit&quot;)</value>
      <webElementGuid>adaef9a1-e9ab-4c33-a8e6-4923848705ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ShippingSubmit']</value>
      <webElementGuid>0fef8125-e3b7-4c5f-9aad-37e8360f2a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shipAddress']/button</value>
      <webElementGuid>4584e521-b2e0-4dd8-b6f0-7c662f8fea70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T.C. Kimlik No'])[1]/following::button[1]</value>
      <webElementGuid>91fc9b9a-97c7-4d89-b6b2-554f95f9fcfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vergi Dairesi:'])[1]/following::button[1]</value>
      <webElementGuid>106b5b54-7887-4457-bd77-30e6f9b2ecea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kredi Kartı'])[1]/preceding::button[1]</value>
      <webElementGuid>830de75f-3a4a-4d68-8b0c-d669e66b97d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iyzico ile öde'])[1]/preceding::button[1]</value>
      <webElementGuid>230e456f-1c72-4d7a-a176-6a7d43a694b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kaydet']/parent::*</value>
      <webElementGuid>a71354e8-c692-4272-bd51-81c9f8c2af3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/form/button</value>
      <webElementGuid>ff23ab62-e93a-4766-aa40-7a8eaa9b8962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ShippingSubmit' and @type = 'button' and (text() = 'Kaydet' or . = 'Kaydet')]</value>
      <webElementGuid>d7490f72-a4d3-4731-95a3-e6de3761e032</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
