<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ad_ShippingNewAddress.LastName</name>
   <tag></tag>
   <elementGuidId>9f0444ed-e125-40b0-aa0a-bd2a62f4ca75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ShippingNewAddress_LastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ShippingNewAddress_LastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4974c52d-ffbe-447d-a6d9-aac451ff1544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return /[a-z]|ö|ş|ç|ü|ğ|ı|İ|\S|/i.test(event.key)</value>
      <webElementGuid>1314fee0-298c-4dc0-b645-30d6b71e146c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>09c09238-1e60-4e3e-945c-9565a79c5597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Soyad</value>
      <webElementGuid>9b31cb3e-c762-41d2-a12d-c07076bc77d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>01ea5b10-d169-454f-bf04-770bdf52e34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ShippingNewAddress_LastName</value>
      <webElementGuid>9f9ea172-d316-4472-b9a5-1f1a21d10c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ShippingNewAddress.LastName</value>
      <webElementGuid>002985b8-c3b1-4c33-99e3-9532d940295c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ShippingNewAddress_LastName&quot;)</value>
      <webElementGuid>7dfad2d8-f8cf-48ca-a09e-7c69a3daf89e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ShippingNewAddress_LastName']</value>
      <webElementGuid>b0682efa-c79d-4fef-94a2-40349c22c1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shipAddress']/div/div/div/div[2]/input</value>
      <webElementGuid>0b9a047e-9630-4557-a280-d38220a9a53e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>531ffa66-332f-4088-a415-930ae3c107e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Soyad' and @type = 'text' and @id = 'ShippingNewAddress_LastName' and @name = 'ShippingNewAddress.LastName']</value>
      <webElementGuid>c9e43878-82b7-435a-ac7f-a748c079ae69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
