<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Soyad_ShippingNewAddress.Title</name>
   <tag></tag>
   <elementGuidId>7413abcf-6096-462d-aae5-a23c688188c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ShippingNewAddress_Title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ShippingNewAddress_Title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09a612c0-806e-4e16-9076-b2e924c19aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fc6d2854-4532-4be6-bfd3-3b23a2871c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Adres Adı</value>
      <webElementGuid>293e24e7-48c1-41bf-9b39-2c38586213b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76c96b3c-7a78-4ccd-8911-0c672434eac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ShippingNewAddress_Title</value>
      <webElementGuid>f5f03299-5473-4e6d-8dbd-cbe3c7c46398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ShippingNewAddress.Title</value>
      <webElementGuid>8aa8893f-c2a0-4f48-969a-80c128f2eb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ShippingNewAddress_Title&quot;)</value>
      <webElementGuid>d509724c-3bee-4e02-bf03-038e9234fd78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ShippingNewAddress_Title']</value>
      <webElementGuid>0cce6b57-5f19-40a4-a562-5c38db66799a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shipAddress']/div/div/div/div[3]/input</value>
      <webElementGuid>56f7de21-acc3-4409-9332-e834fa378727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>42911dba-84cc-4084-90c8-e74363c8090a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Adres Adı' and @type = 'text' and @id = 'ShippingNewAddress_Title' and @name = 'ShippingNewAddress.Title']</value>
      <webElementGuid>71c541df-7b69-4960-9982-a17d8a0258dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
