<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sms Code_smsCode</name>
   <tag></tag>
   <elementGuidId>5932b0bb-e9f3-42c6-ab07-6181757de85b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#smsCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='smsCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30ddf67a-3639-4de0-8023-f1bf9d200b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>be8fbd8d-755a-4ac5-830a-d73ff802f777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Sms Code</value>
      <webElementGuid>8173598f-bb1d-4568-a1f0-04b4f230a884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>smsCode</value>
      <webElementGuid>9aaf53af-66e9-4540-afb0-1b7c642d037d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>smsCode</value>
      <webElementGuid>77665323-a2d0-448d-a491-dfd02678e1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;smsCode&quot;)</value>
      <webElementGuid>75d0f9f2-91d1-4407-a6a6-55364618f091</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='smsCode']</value>
      <webElementGuid>1a3fe0c0-0e57-4d6d-8663-ba5f5e9d72cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='iyzico-3ds-callback-form']/div[2]/input</value>
      <webElementGuid>f110cf3f-49a8-4901-9dc3-c885e6b581cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fbb5c15a-1420-44cd-86ac-7e7705f488e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Sms Code' and @id = 'smsCode' and @name = 'smsCode']</value>
      <webElementGuid>df0b2ea9-0515-4c4a-a550-7cf0a889580b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
