<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Faturam farkl bir adrese gnder_ShippingNewAddress.FirstName</name>
   <tag></tag>
   <elementGuidId>693c8ac0-4f84-4a49-95e8-8e3c78b112b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ShippingNewAddress_FirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ShippingNewAddress_FirstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f23f339f-de50-4fbf-9893-90a02f009336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return /[a-z]|ö|ş|ç|ü|ğ|ı|İ|\S|/i.test(event.key)</value>
      <webElementGuid>9dd2e24d-e275-4b15-8315-17771272d647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>99e90ad4-869c-44e4-8fbc-6e353e682b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ad</value>
      <webElementGuid>f4439e2f-ab77-4895-bb5e-52df6ebf346b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2427664-8383-4b5e-8b41-7f98296da0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ShippingNewAddress_FirstName</value>
      <webElementGuid>4008e664-f012-4128-bf0d-7634ab768ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ShippingNewAddress.FirstName</value>
      <webElementGuid>7ecf31bb-2cf0-437b-8e49-35d07e6f767e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ShippingNewAddress_FirstName&quot;)</value>
      <webElementGuid>78d15111-354d-4e7b-8122-c6a68ce7d58e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ShippingNewAddress_FirstName']</value>
      <webElementGuid>9a5d824b-0784-48cc-8221-a52d7d89a833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shipAddress']/div/div/div/div/input</value>
      <webElementGuid>7bcdf8d0-ea8b-4674-a330-51f0cc16edc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/input</value>
      <webElementGuid>a2b6a05a-2aed-4840-91c6-df18b009839a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Ad' and @type = 'text' and @id = 'ShippingNewAddress_FirstName' and @name = 'ShippingNewAddress.FirstName']</value>
      <webElementGuid>2cc62733-f3b9-4eea-a489-04ecdd4bd8b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
