<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cvc</name>
   <tag></tag>
   <elementGuidId>517c62b1-9c64-4192-8afc-a0a3385bb7db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CardCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CardCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb793774-226e-4fe5-ad67-f91b3d5f0119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Güvenlik Kodu</value>
      <webElementGuid>314991ac-4075-4976-8966-d0d78285f81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control jp-card-invalid</value>
      <webElementGuid>02fd2325-33d7-46b0-9b12-ef5a89511765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bb1f5e8f-8615-4d48-8a77-cce307c22ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b4beceaa-d496-4238-8e68-082975e15999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>payment.cardcode.wrong</value>
      <webElementGuid>ca684640-0827-4ffa-9123-0f60bc263ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[0-9]{3,4}$</value>
      <webElementGuid>31b4d190-4f55-46c8-93c1-edbb963eb647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CardCode</value>
      <webElementGuid>ee9cf5b9-2a36-447b-9a9c-45262c93eefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CardCode</value>
      <webElementGuid>dde456b6-fd35-4796-bbfd-7a3bc175d09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardCode&quot;)</value>
      <webElementGuid>f03dec03-6f8d-45c6-b80b-65588e47353e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CardCode']</value>
      <webElementGuid>5e468b0e-4485-4e08-9d4c-cb785f23a41e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IyzicoCreditCardInfoModel']/div/div/div/div[4]/div/input</value>
      <webElementGuid>959328d4-2a07-4142-a67c-daa5359cbe54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>de2a2aa0-fe8e-4ce2-88cd-c0c59695fc45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Güvenlik Kodu' and @type = 'text' and @id = 'CardCode' and @name = 'CardCode']</value>
      <webElementGuid>74a08041-3eda-4756-b1a1-58111cd67e2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
