<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Adres_ShippingNewAddress.Email</name>
   <tag></tag>
   <elementGuidId>a058e004-c22a-4a1c-b2b8-d6aa9a5458ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ShippingNewAddress_Email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ShippingNewAddress_Email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c41d48de-edd3-420f-a647-896cd1c7362f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>547ebaa0-b823-41a3-987b-d3bd052d08a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>E-Posta</value>
      <webElementGuid>3b57e03d-314b-418f-8f61-e1f6e7e48817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>055c68ff-044f-4d32-9624-f99bd9967b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ShippingNewAddress_Email</value>
      <webElementGuid>d69156f2-aa51-4469-97a4-1908a618c723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ShippingNewAddress.Email</value>
      <webElementGuid>f5340adc-23a3-42b2-a63d-92910d138719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ShippingNewAddress_Email&quot;)</value>
      <webElementGuid>0b6fc071-70d5-479b-a8e6-f0359c65cd3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ShippingNewAddress_Email']</value>
      <webElementGuid>ba6ace5d-3e90-4aa0-a342-64998e5038fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shipAddress']/div/div/div/div[5]/input</value>
      <webElementGuid>08d8a4dd-a237-4ddf-98e8-e85d5f986b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>ebc5097f-4d70-4a88-9225-e5a17a2eb85a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'E-Posta' and @type = 'email' and @id = 'ShippingNewAddress_Email' and @name = 'ShippingNewAddress.Email']</value>
      <webElementGuid>8552e4ca-aa3a-4ae0-b1e0-9684e1ad165d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
