<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ZipPostalCode</name>
   <tag></tag>
   <elementGuidId>9c202cd2-49fb-47f0-96e1-3f5b4c2bc960</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ShippingNewAddress_ZipPostalCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ShippingNewAddress_ZipPostalCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e356646c-2611-47b4-a3ac-41fbbc7581dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ShippingNewAddress.ZipPostalCode</value>
      <webElementGuid>42951431-6e2c-499a-8407-f295da6352ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ShippingNewAddress_ZipPostalCode</value>
      <webElementGuid>441cfd99-5565-47f8-b7e7-c970c8a7e3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>92a5a9c3-4272-4026-b58e-21ec799f2911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>_____</value>
      <webElementGuid>a506d8cf-bee3-4887-aad6-c7d9e8246f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f14a1ac5-2d6d-4b16-846d-4b3553801861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ShippingNewAddress_ZipPostalCode&quot;)</value>
      <webElementGuid>7647fbe2-ff86-4c47-b629-1387b025748c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ShippingNewAddress_ZipPostalCode']</value>
      <webElementGuid>22186946-e370-413f-a054-1162aac5bd42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shipAddress']/div/div/div/div[11]/input</value>
      <webElementGuid>30b25070-6b39-46c6-9056-676e1e935230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>f5e68f89-6991-493f-b8c2-123bd99dec89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ShippingNewAddress.ZipPostalCode' and @id = 'ShippingNewAddress_ZipPostalCode' and @placeholder = '_____']</value>
      <webElementGuid>72305472-d94f-4210-a77e-884776e80636</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
