<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_mahalle</name>
   <tag></tag>
   <elementGuidId>354c48fa-38d3-4ed2-a29f-6d1bc48880c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ShippingNewAddress_TownId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ShippingNewAddress_TownId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>42ac6420-602c-476f-9011-ed560fb4aec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-control</value>
      <webElementGuid>b7ebc275-cb62-43f3-accd-7b86d99ca053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c1d96037-4492-40a2-b504-4bdc39788040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The TownId field is required.</value>
      <webElementGuid>34ea7756-ea7b-40fd-a923-80f06e9dffa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ShippingNewAddress_TownId</value>
      <webElementGuid>80fcff49-1348-402f-a26a-d79412687bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ShippingNewAddress.TownId</value>
      <webElementGuid>01f8357c-db6f-4294-8142-774e6f66c5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ShippingNewAddress_TownId&quot;)</value>
      <webElementGuid>26704371-cb41-478a-ac3a-c40ada0ba1e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ShippingNewAddress_TownId']</value>
      <webElementGuid>5992c50a-d76a-484b-8f5d-588ec62c358b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shipAddress']/div/div/div/div[10]/select</value>
      <webElementGuid>ccd959dc-e6c0-495d-92a7-6704f54cb51e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/select</value>
      <webElementGuid>e04963a5-202d-45de-89de-107eb66f1451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ShippingNewAddress_TownId' and @name = 'ShippingNewAddress.TownId']</value>
      <webElementGuid>44be9655-6ecd-42fd-8a5a-4d5773fccf5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
