<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ilce</name>
   <tag></tag>
   <elementGuidId>eaa93e3e-aaa1-44bf-b90f-8ca1922cc753</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ShippingNewAddress_CountyId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ShippingNewAddress_CountyId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>98207c43-1ddf-480c-9d57-8ff7930ce397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-control</value>
      <webElementGuid>f0983d6b-55e1-49ed-8f96-274021f147ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3f626532-7856-4c68-8abb-c39c3f81072e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The CountyId field is required.</value>
      <webElementGuid>8fb5e794-e6b3-41a4-9db5-3ab110ede644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ShippingNewAddress_CountyId</value>
      <webElementGuid>266f9a7b-58fe-4b4e-89ba-cfa9ca580756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ShippingNewAddress.CountyId</value>
      <webElementGuid>8b4a40c2-3b7b-44dd-a633-35e254df26ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ShippingNewAddress_CountyId&quot;)</value>
      <webElementGuid>e1dc12e8-3096-40ec-b13a-98d8277ff802</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ShippingNewAddress_CountyId']</value>
      <webElementGuid>77b78a79-12c0-4b59-aaef-3a0811a86e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shipAddress']/div/div/div/div[9]/select</value>
      <webElementGuid>c6456ad4-d660-4dc4-90c6-fc75fe50e5d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/select</value>
      <webElementGuid>b31d89dc-e0ca-4a20-9916-7ad439c6d4ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ShippingNewAddress_CountyId' and @name = 'ShippingNewAddress.CountyId']</value>
      <webElementGuid>34b62746-c171-4324-82ad-24e162efda8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
