<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_month</name>
   <tag></tag>
   <elementGuidId>547ea0b9-3f07-4d06-b9b8-94d958434215</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ExpireMonthWrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ExpireMonthWrapper']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cd41e9e4-a60f-45e7-8519-0127e75a16b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExpireMonthWrapper</value>
      <webElementGuid>05f8dfe8-def6-4152-ae3f-e9c486e8e148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-6 col-12</value>
      <webElementGuid>9de211cc-fcbf-4cd6-93d4-90a07365ceab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Son kullanma ay</value>
      <webElementGuid>6e9dfe4a-b80a-4202-b892-2f76082a10eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                         
                                        01
02
03
04
05
06
07
08
09
10
11
12
</value>
      <webElementGuid>e8a402d9-540f-431a-8301-21261be52823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExpireMonthWrapper&quot;)</value>
      <webElementGuid>b8afef1c-e094-45a9-a847-bdb8619a705b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ExpireMonthWrapper']</value>
      <webElementGuid>58f5f090-0c66-4748-a880-9828e294b2e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IyzicoCreditCardInfoModel']/div/div/div/div[3]/div/div/div/select</value>
      <webElementGuid>ec707e28-6127-48d8-b5e5-c56d8653d067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kart numarası:'])[1]/following::select[1]</value>
      <webElementGuid>a0c9baca-0e01-4d74-a697-894baddf48de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kart Sahibinin Adı:'])[1]/following::select[1]</value>
      <webElementGuid>425bd687-7e70-413a-83ec-07e5adcc7fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Son kullanma ay'])[1]/preceding::select[1]</value>
      <webElementGuid>b93f1de9-3f66-42cf-9f80-84805a7e9741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Son kullanma yıl'])[1]/preceding::select[2]</value>
      <webElementGuid>20c70c2e-63ed-442b-98d5-3aa5e8d33056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/select</value>
      <webElementGuid>e13631db-4c16-4cf0-a93e-e7ca86904b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ExpireMonthWrapper' and (text() = '
                                         
                                        01
02
03
04
05
06
07
08
09
10
11
12
' or . = '
                                         
                                        01
02
03
04
05
06
07
08
09
10
11
12
')]</value>
      <webElementGuid>426eda5e-bba9-4a0d-9aef-d504bc57f578</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
