<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_contract</name>
   <tag></tag>
   <elementGuidId>58a0b1fc-10dc-4fda-a770-61b06fff240c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.custom-control-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='legal-issue']/div/div[2]/label/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ee5ee7df-2277-43c4-8236-a45d672ba1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-label</value>
      <webElementGuid>41cf8fd5-ad04-40a9-8b96-cb4433b2fd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;legal-issue&quot;)/div[@class=&quot;col-12&quot;]/div[@class=&quot;terms-of-service&quot;]/label[@class=&quot;custom-control custom-checkbox&quot;]/div[@class=&quot;checkbox-area&quot;]/span[@class=&quot;custom-control-label&quot;]</value>
      <webElementGuid>d2af9de1-0c16-45c1-bddc-b8775b4e1787</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='legal-issue']/div/div[2]/label/div/span</value>
      <webElementGuid>2748b327-e046-486c-b22b-653a059cd46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/span</value>
      <webElementGuid>343eec1f-af55-4d9f-a284-8f0c81325473</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
