<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Adres Ad_ShippingNewAddress.Address1</name>
   <tag></tag>
   <elementGuidId>669218f3-6b03-4a22-9d3b-b6d2f78600d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ShippingNewAddress_Address1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ShippingNewAddress_Address1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c41df1d3-f729-4fb3-956a-a0c7255e9db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>d960f604-be8b-45a0-af64-0cde23a9d6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7247ae37-8ac6-428c-a28b-4b930c974192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Adres</value>
      <webElementGuid>d793ad0b-f40c-4691-b4f8-069008ccd4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ShippingNewAddress_Address1</value>
      <webElementGuid>0625be52-2bda-41be-ac17-62204d1db177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ShippingNewAddress.Address1</value>
      <webElementGuid>ec5eb2ae-3524-416c-8139-f126c2af9222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ShippingNewAddress_Address1&quot;)</value>
      <webElementGuid>039aeeba-848b-4291-961a-daadeabf16e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ShippingNewAddress_Address1']</value>
      <webElementGuid>25ccea3a-ced6-4c50-80c0-eb1e76c57903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shipAddress']/div/div/div/div[4]/textarea</value>
      <webElementGuid>24256dd1-6c6f-4f7a-8d2c-fff1289451f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>7c45018a-e88f-4540-b186-2a38c2995961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Adres' and @id = 'ShippingNewAddress_Address1' and @name = 'ShippingNewAddress.Address1']</value>
      <webElementGuid>270bdf80-c435-4c3a-a063-ef23b078349a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
